config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "chatrooms#index"

  resources :chatrooms, only: [:index, :show] do 
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  after_create_commit {
    broadcast_append_to "chatroom_#{chatroom.id}",
      target: "messages",
      partial: 'messages/message'
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    
    @message.save
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Chatrooms 💬</h1>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @chatrooms.each do |chatroom| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= chatroom.name %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <%= link_to "View", chatroom_path(chatroom), class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<style>
  [data-sender="<%= dom_id(current_user) %>"] {
    display: flex;
    justify-content: flex-end
  }

  [data-sender="<%= dom_id(current_user) %>"] .chat-img {
    order: 2;
    margin-left: 10px;
  }

  [data-sender="<%= dom_id(current_user) %>"] .chat-bubble {
    background-color: #5046E5 !important;
    color: #fff !important;
    padding: 10px;
  }
</style>

<%= turbo_stream_from dom_id(@chatroom) %>

<div class="flex flex-col flex-grow w-full bg-white shadow-xl rounded-lg overflow-hidden mx-auto h-screen">
  <div id="messages" class="flex flex-col flex-grow h-0 p-4 overflow-auto bg-gray-100">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>

  <div class="p-4">
    <%= form_with model: @message, url: chatroom_messages_path(@chatroom), data: {controller: "form-reset", action: "turbo:submit-end->form-reset#reset"} do |f| %>
      <%= f.text_area :content, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
      <%= f.submit "Send", class: "bg-indigo-600 px-3 py-1 rounded-md text-white float-right mt-10" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="flex mt-2 space-x-3 w-full" data-sender="<%= dom_id(message.user) %>">
  <div class="chat-img flex-shrink-0 h-10 w-10 rounded-full bg-gray-300">
  </div>
  <div class="max-w-xs">
    <div class="bg-gray-300 p-3 rounded-lg chat-bubble">
      <strong class="text-sm"><%= message.user.email %></strong>
      <p class="text-sm"><%= message.content %></p>
    </div>
    <span class="text-xs text-gray-500 leading-none"><%= time_ago_in_words(message.created_at) %></span>
  </div>
</div>